language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - nightly

matrix:
  allow_failures:
  - php: nightly

env:
  - COMPOSER_OPTS=""
  - COMPOSER_OPTS="--prefer-lowest"

install:
  - composer update $COMPOSER_OPTS

script:
  - vendor/bin/phpunit

jobs:
  include:

    - stage: dependencies
      script:
        - vendor/bin/composer-require-checker

    - stage: coding standards
      script:
        - vendor/bin/phpcs --standard=PSR1,PSR2,PSR12 src tests

    - stage: code quality
      script:
        - vendor/bin/phpstan analyse --level=max src
        - vendor/bin/phpstan analyse --level=max --configuration=phpstan-tests.neon tests

    - stage: coverage
      script:
        - vendor/bin/phpunit --coverage-clover=coverage.xml
        - bash <(curl -s https://codecov.io/bash)

git:
  depth: 5

group: travis_latest
